import type { PlayerInterface } from '@/interfaces/PlayerInterface.js';

const seedTimestamp = '2026-09-01T00:00:00.000Z';

export const playerSeedData: PlayerInterface[] = [
  {
    id: 'player-001',
    name: 'Samuel Torres',
    position: 'Forward',
    status: 'active',
    teamId: 'team-001',
    goals: 12,
    assists: 5,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'player-002',
    name: 'Mateo Restrepo',
    position: 'Midfielder',
    status: 'active',
    teamId: 'team-001',
    goals: 4,
    assists: 9,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'player-003',
    name: 'Thiago Ferreyra',
    position: 'Forward',
    status: 'active',
    teamId: 'team-002',
    goals: 15,
    assists: 6,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'player-004',
    name: 'Nicolas Acosta',
    position: 'Defender',
    status: 'active',
    teamId: 'team-002',
    goals: 1,
    assists: 2,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'player-005',
    name: 'Lucas Ribeiro',
    position: 'Winger',
    status: 'active',
    teamId: 'team-003',
    goals: 8,
    assists: 10,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'player-006',
    name: 'Gabriel Costa',
    position: 'Goalkeeper',
    status: 'active',
    teamId: 'team-003',
    goals: 0,
    assists: 0,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'player-007',
    name: 'Martin Silva',
    position: 'Midfielder',
    status: 'active',
    teamId: 'team-004',
    goals: 5,
    assists: 7,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'player-008',
    name: 'Facundo Pereira',
    position: 'Defender',
    status: 'injured',
    teamId: 'team-004',
    goals: 2,
    assists: 1,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'player-009',
    name: 'Daniel Vega',
    position: 'Forward',
    status: 'free-agent',
    teamId: null,
    goals: 6,
    assists: 3,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
