import type { PlayerInterface } from '@/interfaces/PlayerInterface.js';
import {
  buenosAiresSur,
  medellinCondors,
  montevideoCeleste,
  rioStars,
} from '@/stores/teamseeder.js';

const defaultPlayerValues: PlayerInterface = {
  id: '',
  name: '',
  imageURL: '',
  position: '',
  dateOfBirth: '',
  nationality: '',
  height: 0,
  weight: 0,
  jerseyNumber: 0,
  status: 'active',
  team: null,
  matchesPlayed: 0,
  minutesPlayed: 0,
  goals: 0,
  assists: 0,
  yellowCards: 0,
  redCards: 0,
  foulsCommitted: 0,
  foulsSuffered: 0,
  passes: 0,
  keyPasses: 0,
  shots: 0,
  shotsOnTarget: 0,
  tackles: 0,
  interceptions: 0,
  dribbles: 0,
  dribblesSuccess: 0,
  duelsWon: 0,
  duelsLost: 0,
  createdAt: '2026-09-01T00:00:00.000Z',
  updatedAt: '2026-09-01T00:00:00.000Z',
};

export const playerSeedData: PlayerInterface[] = [
  {
    ...defaultPlayerValues,
    id: 'player-001',
    name: 'Samuel Torres',
    imageURL: 'https://placehold.co/256x256/0f766e/ffffff?text=ST',
    position: 'Forward',
    dateOfBirth: '1999-04-18',
    nationality: 'Colombia',
    height: 181,
    weight: 76,
    jerseyNumber: 9,
    team: medellinCondors,
    matchesPlayed: 18,
    minutesPlayed: 1520,
    goals: 12,
    assists: 5,
    yellowCards: 3,
    foulsCommitted: 19,
    foulsSuffered: 28,
    passes: 486,
    keyPasses: 31,
    shots: 64,
    shotsOnTarget: 38,
    tackles: 12,
    interceptions: 7,
    dribbles: 58,
    dribblesSuccess: 37,
    duelsWon: 82,
    duelsLost: 49,
  },
  {
    ...defaultPlayerValues,
    id: 'player-002',
    name: 'Mateo Restrepo',
    imageURL: 'https://placehold.co/256x256/0f766e/ffffff?text=MR',
    position: 'Midfielder',
    dateOfBirth: '2000-09-02',
    nationality: 'Colombia',
    height: 176,
    weight: 70,
    jerseyNumber: 8,
    team: medellinCondors,
    matchesPlayed: 19,
    minutesPlayed: 1640,
    goals: 4,
    assists: 9,
    yellowCards: 5,
    foulsCommitted: 27,
    foulsSuffered: 35,
    passes: 1128,
    keyPasses: 54,
    shots: 32,
    shotsOnTarget: 15,
    tackles: 48,
    interceptions: 36,
    dribbles: 71,
    dribblesSuccess: 46,
    duelsWon: 103,
    duelsLost: 67,
  },
  {
    ...defaultPlayerValues,
    id: 'player-003',
    name: 'Thiago Ferreyra',
    imageURL: 'https://placehold.co/256x256/2563eb/ffffff?text=TF',
    position: 'Forward',
    dateOfBirth: '1998-01-27',
    nationality: 'Argentina',
    height: 184,
    weight: 79,
    jerseyNumber: 10,
    team: buenosAiresSur,
    matchesPlayed: 20,
    minutesPlayed: 1715,
    goals: 15,
    assists: 6,
    yellowCards: 2,
    foulsCommitted: 17,
    foulsSuffered: 41,
    passes: 523,
    keyPasses: 38,
    shots: 79,
    shotsOnTarget: 46,
    tackles: 9,
    interceptions: 5,
    dribbles: 83,
    dribblesSuccess: 55,
    duelsWon: 91,
    duelsLost: 52,
  },
  {
    ...defaultPlayerValues,
    id: 'player-004',
    name: 'Nicolas Acosta',
    imageURL: 'https://placehold.co/256x256/2563eb/ffffff?text=NA',
    position: 'Defender',
    dateOfBirth: '1997-06-14',
    nationality: 'Argentina',
    height: 188,
    weight: 83,
    jerseyNumber: 4,
    team: buenosAiresSur,
    matchesPlayed: 19,
    minutesPlayed: 1682,
    goals: 1,
    assists: 2,
    yellowCards: 6,
    redCards: 1,
    foulsCommitted: 35,
    foulsSuffered: 14,
    passes: 986,
    keyPasses: 12,
    shots: 15,
    shotsOnTarget: 6,
    tackles: 72,
    interceptions: 61,
    dribbles: 18,
    dribblesSuccess: 12,
    duelsWon: 138,
    duelsLost: 59,
  },
  {
    ...defaultPlayerValues,
    id: 'player-005',
    name: 'Lucas Ribeiro',
    imageURL: 'https://placehold.co/256x256/f59e0b/111827?text=LR',
    position: 'Winger',
    dateOfBirth: '2001-02-11',
    nationality: 'Brazil',
    height: 174,
    weight: 68,
    jerseyNumber: 11,
    team: rioStars,
    matchesPlayed: 17,
    minutesPlayed: 1360,
    goals: 8,
    assists: 10,
    yellowCards: 2,
    foulsCommitted: 16,
    foulsSuffered: 46,
    passes: 674,
    keyPasses: 49,
    shots: 51,
    shotsOnTarget: 29,
    tackles: 24,
    interceptions: 15,
    dribbles: 112,
    dribblesSuccess: 78,
    duelsWon: 96,
    duelsLost: 61,
  },
  {
    ...defaultPlayerValues,
    id: 'player-006',
    name: 'Gabriel Costa',
    imageURL: 'https://placehold.co/256x256/f59e0b/111827?text=GC',
    position: 'Goalkeeper',
    dateOfBirth: '1996-10-05',
    nationality: 'Brazil',
    height: 193,
    weight: 88,
    jerseyNumber: 1,
    team: rioStars,
    matchesPlayed: 20,
    minutesPlayed: 1800,
    yellowCards: 1,
    foulsCommitted: 3,
    foulsSuffered: 2,
    passes: 742,
    keyPasses: 3,
    tackles: 2,
    interceptions: 18,
    duelsWon: 21,
    duelsLost: 8,
  },
  {
    ...defaultPlayerValues,
    id: 'player-007',
    name: 'Martin Silva',
    imageURL: 'https://placehold.co/256x256/38bdf8/082f49?text=MS',
    position: 'Midfielder',
    dateOfBirth: '1999-12-21',
    nationality: 'Uruguay',
    height: 179,
    weight: 73,
    jerseyNumber: 6,
    team: montevideoCeleste,
    matchesPlayed: 18,
    minutesPlayed: 1554,
    goals: 5,
    assists: 7,
    yellowCards: 4,
    foulsCommitted: 31,
    foulsSuffered: 29,
    passes: 1054,
    keyPasses: 44,
    shots: 37,
    shotsOnTarget: 18,
    tackles: 57,
    interceptions: 42,
    dribbles: 53,
    dribblesSuccess: 34,
    duelsWon: 111,
    duelsLost: 72,
  },
  {
    ...defaultPlayerValues,
    id: 'player-008',
    name: 'Facundo Pereira',
    imageURL: 'https://placehold.co/256x256/38bdf8/082f49?text=FP',
    position: 'Defender',
    dateOfBirth: '1998-08-30',
    nationality: 'Uruguay',
    height: 186,
    weight: 81,
    jerseyNumber: 3,
    status: 'injured',
    team: montevideoCeleste,
    matchesPlayed: 14,
    minutesPlayed: 1198,
    goals: 2,
    assists: 1,
    yellowCards: 5,
    foulsCommitted: 28,
    foulsSuffered: 12,
    passes: 721,
    keyPasses: 9,
    shots: 12,
    shotsOnTarget: 5,
    tackles: 59,
    interceptions: 48,
    dribbles: 14,
    dribblesSuccess: 8,
    duelsWon: 104,
    duelsLost: 43,
  },
  {
    ...defaultPlayerValues,
    id: 'player-009',
    name: 'Daniel Vega',
    imageURL: 'https://placehold.co/256x256/64748b/ffffff?text=DV',
    position: 'Forward',
    dateOfBirth: '2002-05-16',
    nationality: 'Chile',
    height: 180,
    weight: 75,
    jerseyNumber: 19,
    status: 'free-agent',
    team: null,
    matchesPlayed: 10,
    minutesPlayed: 704,
    goals: 6,
    assists: 3,
    yellowCards: 1,
    foulsCommitted: 11,
    foulsSuffered: 18,
    passes: 264,
    keyPasses: 19,
    shots: 34,
    shotsOnTarget: 21,
    tackles: 8,
    interceptions: 4,
    dribbles: 39,
    dribblesSuccess: 25,
    duelsWon: 47,
    duelsLost: 31,
  },
];
